/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_poo;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import proyecto_poo.Clases_unicas.Rutas;
import proyecto_poo.Clases_unicas.Tickets;
import proyecto_poo.Clases_unicas.Viajes;

/**
 *
 * @author albert luna
 */
public class Impresion_ticket extends javax.swing.JFrame {

    /**
     * Creates new form Impresion_ticket
     */
    public Impresion_ticket() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        
        tb_codigo_ticket.setEditable(false);
        tb_salida.setEditable(false);
        tb_destino.setEditable(false);
        tb_fecha.setEditable(false);
        tb_hora_salida.setEditable(false);
        tb_precio.setEditable(false);
        tb_asiento.setEditable(false);
        tb_usuario.setEditable(false);
        tb_autobus.setEditable(false);
        
        Archivo arc = new Archivo();
        Tickets t = Funciones.Ticket_general;
        Viajes v =  (Viajes) arc.buscar_archivo("Viajes",t.getCodigo_viaje());
        Rutas r = (Rutas) arc.buscar_archivo("Rutas",v.getCodigo_ruta());
        
        this.tb_codigo_ticket.setText(Integer.toString(t.getCodigo_ticket()));
        this.tb_salida.setText(r.getLugar_salida());
        this.tb_destino.setText(r.getLugar_llegada());
        this.tb_fecha.setText(v.getFecha());
        this.tb_hora_salida.setText(v.getHora_salida());
        this.tb_precio.setText(Float.toString(v.getPrecio_ticket()));
        String asiento = (Integer.toString(t.getFila())) + "," + (Integer.toString(t.getColumna()));
        this.tb_asiento.setText(asiento);
        this.tb_usuario.setText(Funciones.usuario_general.getNombre_usuario());
        this.tb_autobus.setText(Integer.toString(v.getCodigo_autobus()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_nombre_sistema = new javax.swing.JLabel();
        lb_destino = new javax.swing.JLabel();
        lb_salida = new javax.swing.JLabel();
        lb_codigo_ticket = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        lb_hora_Salida = new javax.swing.JLabel();
        lb_precio = new javax.swing.JLabel();
        lb_usuario = new javax.swing.JLabel();
        lb_asiento = new javax.swing.JLabel();
        lb_codigo_autobus = new javax.swing.JLabel();
        tb_fecha = new javax.swing.JTextField();
        tb_codigo_ticket = new javax.swing.JTextField();
        tb_salida = new javax.swing.JTextField();
        tb_hora_salida = new javax.swing.JTextField();
        tb_precio = new javax.swing.JTextField();
        tb_asiento = new javax.swing.JTextField();
        tb_usuario = new javax.swing.JTextField();
        tb_autobus = new javax.swing.JTextField();
        tb_destino = new javax.swing.JTextField();
        bt_salir = new javax.swing.JButton();
        lb_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_nombre_sistema.setText("Sistema de Transporte");
        getContentPane().add(lb_nombre_sistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 30));

        lb_destino.setText("Destino:");
        getContentPane().add(lb_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 40, -1));

        lb_salida.setText("Salida:");
        getContentPane().add(lb_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lb_codigo_ticket.setText("Codigo:");
        getContentPane().add(lb_codigo_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lb_fecha.setText("Fecha:");
        getContentPane().add(lb_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        lb_hora_Salida.setText("Hora de salida:");
        getContentPane().add(lb_hora_Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lb_precio.setText("Precio:");
        getContentPane().add(lb_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        lb_usuario.setText("Usuario:");
        getContentPane().add(lb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 50, -1));

        lb_asiento.setText("Asiento:");
        getContentPane().add(lb_asiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        lb_codigo_autobus.setText("Autobus:");
        getContentPane().add(lb_codigo_autobus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
        getContentPane().add(tb_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 110, -1));
        getContentPane().add(tb_codigo_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 110, -1));
        getContentPane().add(tb_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, -1));
        getContentPane().add(tb_hora_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, -1));
        getContentPane().add(tb_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 110, -1));
        getContentPane().add(tb_asiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 110, -1));
        getContentPane().add(tb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 110, -1));
        getContentPane().add(tb_autobus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 110, -1));
        getContentPane().add(tb_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 110, -1));

        bt_salir.setText("Salir");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });
        getContentPane().add(bt_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 70, -1));

        lb_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/crumpled-white-paper-texture-melemel-jpeg_260159.jpg"))); // NOI18N
        getContentPane().add(lb_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bt_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impresion_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impresion_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impresion_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impresion_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Impresion_ticket().setVisible(true);
                } catch (IOException | ClassNotFoundException ex) {
                    Logger.getLogger(Impresion_ticket.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_salir;
    private javax.swing.JLabel lb_asiento;
    private javax.swing.JLabel lb_codigo_autobus;
    private javax.swing.JLabel lb_codigo_ticket;
    private javax.swing.JLabel lb_destino;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_fondo;
    private javax.swing.JLabel lb_hora_Salida;
    private javax.swing.JLabel lb_nombre_sistema;
    private javax.swing.JLabel lb_precio;
    private javax.swing.JLabel lb_salida;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JTextField tb_asiento;
    private javax.swing.JTextField tb_autobus;
    private javax.swing.JTextField tb_codigo_ticket;
    private javax.swing.JTextField tb_destino;
    private javax.swing.JTextField tb_fecha;
    private javax.swing.JTextField tb_hora_salida;
    private javax.swing.JTextField tb_precio;
    private javax.swing.JTextField tb_salida;
    private javax.swing.JTextField tb_usuario;
    // End of variables declaration//GEN-END:variables
}
