/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_poo;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyecto_poo.Clases_unicas.Usuarios;

/**
 *
 * @author albert luna
 */
public class Login extends javax.swing.JFrame 
{

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_salir = new javax.swing.JButton();
        bt_entrar = new javax.swing.JButton();
        lb_usuario = new javax.swing.JLabel();
        lb_password = new javax.swing.JLabel();
        tb_usuario = new javax.swing.JTextField();
        tb_password = new javax.swing.JPasswordField();
        lb_encabezado = new javax.swing.JLabel();
        lb_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Login"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_salir.setText("Salir");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });
        getContentPane().add(bt_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 90, -1));

        bt_entrar.setText("Entrar");
        bt_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 90, -1));

        lb_usuario.setText("Usuario");
        getContentPane().add(lb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        lb_password.setText("Password");
        getContentPane().add(lb_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        getContentPane().add(tb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, -1));
        getContentPane().add(tb_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 140, -1));

        lb_encabezado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_encabezado.setText("Sistema de transporte");
        getContentPane().add(lb_encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        lb_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/fondo-verde-brillante-5050.jpg"))); // NOI18N
        getContentPane().add(lb_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 287));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bt_salirActionPerformed

    private void bt_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarActionPerformed
        // TODO add your handling code here:
        String nombre = tb_usuario.getText();
        String clave = new String(tb_password.getPassword());
        
        Usuarios u = new Usuarios();
        
        try 
        {
            if(u.ingresar_sistema(nombre, clave))
            {
                //entrar al menu principal.
                Menu_principal mp = new Menu_principal();
                mp.setVisible(true);
                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Sus credenciales son incorrectas");
                tb_usuario.setText("");
                tb_password.setText("");
                tb_usuario.requestFocus();
            }
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex) 
        {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_entrar;
    private javax.swing.JButton bt_salir;
    private javax.swing.JLabel lb_encabezado;
    private javax.swing.JLabel lb_fondo;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JPasswordField tb_password;
    private javax.swing.JTextField tb_usuario;
    // End of variables declaration//GEN-END:variables
}
