/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_poo;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyecto_poo.Clases_unicas.Rutas;

/**
 *
 * @author albert luna
 */
public class Mantenimiento_rutas extends javax.swing.JFrame {

    /**
     * Creates new form Mantenimiento_rutas
     * @throws java.io.IOException
     * @throws java.io.FileNotFoundException
     * @throws java.lang.ClassNotFoundException
     */
    public Mantenimiento_rutas() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.tb_codigo.setEditable(false);
        
        llenar_cb_rutas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_lugar_salida = new javax.swing.JLabel();
        lb_lugar_llegada = new javax.swing.JLabel();
        lb_distancia = new javax.swing.JLabel();
        tb_lugar_salida = new javax.swing.JTextField();
        tb_lugar_llegada = new javax.swing.JTextField();
        tb_distancia = new javax.swing.JTextField();
        bt_guardar = new javax.swing.JButton();
        bt_nuevo = new javax.swing.JButton();
        bt_salir = new javax.swing.JButton();
        bt_desactivar = new javax.swing.JButton();
        bt_activar = new javax.swing.JButton();
        lb_rutas = new javax.swing.JLabel();
        cb_rutas = new javax.swing.JComboBox<>();
        bt_elegir = new javax.swing.JButton();
        lb_codigo = new javax.swing.JLabel();
        tb_codigo = new javax.swing.JTextField();
        cb_estado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lb_lugar_salida.setText("Lugar Salida");

        lb_lugar_llegada.setText("Lugar Llegada");

        lb_distancia.setText("Distancia");

        tb_distancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tb_distanciaKeyTyped(evt);
            }
        });

        bt_guardar.setText("Guardar");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        bt_nuevo.setText("Nuevo");
        bt_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevoActionPerformed(evt);
            }
        });

        bt_salir.setText("Salir");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        bt_desactivar.setText("Desactivar");
        bt_desactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_desactivarActionPerformed(evt);
            }
        });

        bt_activar.setText("Activar");
        bt_activar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_activarActionPerformed(evt);
            }
        });

        lb_rutas.setText("Rutas");

        bt_elegir.setText("Elegir");
        bt_elegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_elegirActionPerformed(evt);
            }
        });

        lb_codigo.setText("Codigo");

        cb_estado.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_lugar_salida)
                                .addGap(22, 22, 22)
                                .addComponent(tb_lugar_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(lb_lugar_llegada)
                                .addGap(13, 13, 13)
                                .addComponent(tb_lugar_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_codigo)
                                    .addComponent(lb_distancia))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tb_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(tb_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(120, 120, 120)
                                        .addComponent(cb_estado)))))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lb_rutas)
                        .addGap(24, 24, 24)
                        .addComponent(cb_rutas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(bt_elegir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_desactivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_activar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_guardar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_lugar_salida)
                            .addComponent(tb_lugar_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_lugar_llegada)
                            .addComponent(tb_lugar_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_nuevo)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_distancia)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tb_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_estado)))
                        .addGap(14, 14, 14)))
                .addComponent(bt_activar)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_codigo)
                    .addComponent(tb_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(bt_desactivar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_rutas, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_rutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_elegir))
                .addGap(10, 10, 10)
                .addComponent(bt_salir)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bt_salirActionPerformed

    private void bt_elegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_elegirActionPerformed
        // TODO add your handling code here:
        Archivo arc = new Archivo();
        int codigo_ruta = Funciones.extraer_codigo(cb_rutas.getSelectedItem().toString());
        try 
        {
            Rutas r = (Rutas) arc.buscar_archivo("Rutas", codigo_ruta);
            this.tb_lugar_salida.setText(r.getLugar_salida());
            this.tb_lugar_llegada.setText(r.getLugar_llegada());
            this.tb_distancia.setText(Float.toString(r.getDistancia()));
            this.tb_codigo.setText(Integer.toString(r.getCodigo_ruta()));
            this.cb_estado.setSelected(r.isEstado());
        } 
        catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Mantenimiento_rutas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_elegirActionPerformed

    private void bt_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevoActionPerformed
        // TODO add your handling code here:
        this.tb_lugar_salida.setText("");
        this.tb_lugar_llegada.setText("");
        this.tb_distancia.setText("");
        this.tb_codigo.setText("");
        this.cb_estado.setSelected(false);
        try {        
            llenar_cb_rutas();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Mantenimiento_rutas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_nuevoActionPerformed

    private void bt_activarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_activarActionPerformed
        // TODO add your handling code here:
        if("".equals(tb_codigo.getText()))
        {
            JOptionPane.showMessageDialog(this,"Debe seleccionar una ruta para poder activarla");
            return;
        }
        
        Archivo arc = new Archivo();
        try {
            int codigo = Integer.valueOf(tb_codigo.getText());
            Rutas r = (Rutas) arc.buscar_archivo("Rutas",codigo);
            r.setEstado(true);
            arc.actualizar_archivo("Rutas", r,codigo);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Mantenimiento_rutas.class.getName()).log(Level.SEVERE, null, ex);
        }
        bt_nuevo.doClick();
    }//GEN-LAST:event_bt_activarActionPerformed

    private void bt_desactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_desactivarActionPerformed
        // TODO add your handling code here:
        if("".equals(tb_codigo.getText()))
        {
            JOptionPane.showMessageDialog(this,"Debe seleccionar una ruta para poder activarla");
            return;
        }
        
        Archivo arc = new Archivo();
        try {
            int codigo = Integer.valueOf(tb_codigo.getText());
            Rutas r = (Rutas) arc.buscar_archivo("Rutas",codigo);
            r.setEstado(false);
            arc.actualizar_archivo("Rutas", r,codigo);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Mantenimiento_rutas.class.getName()).log(Level.SEVERE, null, ex);
        }
        bt_nuevo.doClick();
    }//GEN-LAST:event_bt_desactivarActionPerformed

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        // TODO add your handling code here:
        if(!validar())
        {
                JOptionPane.showMessageDialog(this,"Debe llenar todos los campos");
                return;
        }
        
        if("".equals(tb_codigo.getText()))
        {
            Rutas r;
            try {
                tb_codigo.setText(Integer.toString(Funciones.generar_codigo_automatico("Rutas")));
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Mantenimiento_rutas.class.getName()).log(Level.SEVERE, null, ex);
            }
            r = recoger_datos();
            Archivo arc = new Archivo();
            arc.insertar_archivo("Rutas", r);
            bt_nuevo.doClick();
        }
        else
        {
            Rutas r = recoger_datos();
            Archivo arc = new Archivo();
            try {
                arc.actualizar_archivo("Rutas",r,r.getCodigo_ruta());
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Mantenimiento_rutas.class.getName()).log(Level.SEVERE, null, ex);
            }
            bt_nuevo.doClick();
        }
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void tb_distanciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_distanciaKeyTyped
        // TODO add your handling code here:
        Funciones.solo_numeros(evt,this.tb_distancia);
    }//GEN-LAST:event_tb_distanciaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento_rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Mantenimiento_rutas().setVisible(true);
                } catch (IOException | ClassNotFoundException ex) {
                    Logger.getLogger(Mantenimiento_rutas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public boolean validar()
    {
        if("".equals(this.tb_lugar_salida.getText()) || "".equals(this.tb_lugar_llegada.getText()) || "".equals(this.tb_distancia.getText()))
        {
            return false;
        }
        return true;
    }
    
    public void llenar_cb_rutas() throws IOException, FileNotFoundException, ClassNotFoundException
    {
        cb_rutas.removeAllItems();
        Archivo arc = new Archivo();
        ArrayList<Rutas> lista;
        lista = arc.leer_archivo("Rutas");
        String cadena;
        
        for(Rutas elemento : lista)
        {
            cadena = elemento.getCodigo_ruta() + " " + elemento.getLugar_llegada();
            this.cb_rutas.addItem(cadena);
        }
    }
    
    public Rutas recoger_datos()
    {
        
        Rutas r = new Rutas();
        
        r.setCodigo_ruta(Integer.valueOf(tb_codigo.getText()));
        r.setLugar_salida(tb_lugar_salida.getText());
        r.setLugar_llegada(tb_lugar_llegada.getText());
        r.setDistancia(Float.valueOf(tb_distancia.getText()));
        r.setEstado(cb_estado.isSelected());
        
        return r;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_activar;
    private javax.swing.JButton bt_desactivar;
    private javax.swing.JButton bt_elegir;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_nuevo;
    private javax.swing.JButton bt_salir;
    private javax.swing.JCheckBox cb_estado;
    private javax.swing.JComboBox<String> cb_rutas;
    private javax.swing.JLabel lb_codigo;
    private javax.swing.JLabel lb_distancia;
    private javax.swing.JLabel lb_lugar_llegada;
    private javax.swing.JLabel lb_lugar_salida;
    private javax.swing.JLabel lb_rutas;
    private javax.swing.JTextField tb_codigo;
    private javax.swing.JTextField tb_distancia;
    private javax.swing.JTextField tb_lugar_llegada;
    private javax.swing.JTextField tb_lugar_salida;
    // End of variables declaration//GEN-END:variables
}
