/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_poo;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author albert luna
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_fondo = new javax.swing.JLabel();
        mb_barra_menu = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mi_mantenimeinto_rutas = new javax.swing.JMenuItem();
        mi_mantenimiento_viajes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mi_consulta_tickets = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/ws_Black_&_Green_Carbon_1680x1050.jpg"))); // NOI18N
        getContentPane().add(lb_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 798, 311));

        jMenu3.setText("Mantenimientos");

        mi_mantenimeinto_rutas.setText("Rutas");
        mi_mantenimeinto_rutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_mantenimeinto_rutasActionPerformed(evt);
            }
        });
        jMenu3.add(mi_mantenimeinto_rutas);

        mi_mantenimiento_viajes.setText("Viajes");
        mi_mantenimiento_viajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_mantenimiento_viajesActionPerformed(evt);
            }
        });
        jMenu3.add(mi_mantenimiento_viajes);

        mb_barra_menu.add(jMenu3);

        jMenu4.setText("Consultas");

        mi_consulta_tickets.setText("Tickets");
        mi_consulta_tickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_consulta_ticketsActionPerformed(evt);
            }
        });
        jMenu4.add(mi_consulta_tickets);

        mb_barra_menu.add(jMenu4);

        jMenu5.setText("Procesos");

        jMenuItem1.setText("Vender Tickets");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        mb_barra_menu.add(jMenu5);

        jMenu1.setText("Cerrar sesion");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        mb_barra_menu.add(jMenu1);

        setJMenuBar(mb_barra_menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        int showConfirmDialog = JOptionPane.showConfirmDialog(this,"Esta seguro que desea cerrar esta sesion","Confirmar cierre de sesion",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(showConfirmDialog == 0)
        {
            Login lg = new Login();
            lg.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Venta_tickets vt;
        try {
            vt = new Venta_tickets();
            vt.setVisible(true);
            dispose();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Menu_principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mi_mantenimeinto_rutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_mantenimeinto_rutasActionPerformed
        try {
            // TODO add your handling code here:
            Mantenimiento_rutas mr = new Mantenimiento_rutas();
            mr.setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Menu_principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_mantenimeinto_rutasActionPerformed

    private void mi_consulta_ticketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_consulta_ticketsActionPerformed
        try {
            // TODO add your handling code here:
            Consulta_tickets ct = new Consulta_tickets();
            ct.setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Menu_principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mi_consulta_ticketsActionPerformed

    private void mi_mantenimiento_viajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_mantenimiento_viajesActionPerformed
        // TODO add your handling code here:
        Mantenimiento_viajes mv;
        try {
            mv = new Mantenimiento_viajes();
            mv.setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Menu_principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_mantenimiento_viajesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lb_fondo;
    private javax.swing.JMenuBar mb_barra_menu;
    private javax.swing.JMenuItem mi_consulta_tickets;
    private javax.swing.JMenuItem mi_mantenimeinto_rutas;
    private javax.swing.JMenuItem mi_mantenimiento_viajes;
    // End of variables declaration//GEN-END:variables
}
