/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_poo;

import java.awt.event.ItemEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import proyecto_poo.Clases_unicas.Autobus;
import proyecto_poo.Clases_unicas.Rutas;
import proyecto_poo.Clases_unicas.Tickets;
import proyecto_poo.Clases_unicas.Viajes;

/**
 *
 * @author albert luna
 */
public final class Venta_tickets extends javax.swing.JFrame {

    /**
     * Creates new form Venta_tickets
     * @throws java.io.IOException
     * @throws java.io.FileNotFoundException
     * @throws java.lang.ClassNotFoundException
     */
    public Venta_tickets() throws IOException, FileNotFoundException, ClassNotFoundException  
    {
        initComponents();
        this.setLocationRelativeTo(null);
        tb_precio_asiento.setEditable(false);
        tb_total.setEditable(false);
        cb_ruta.removeAllItems();
        cb_viaje.removeAllItems();
        cb_cant_asientos.removeAllItems();
                
       llenar_cb_rutas();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_ruta = new javax.swing.JComboBox<>();
        cb_viaje = new javax.swing.JComboBox<>();
        lb_viaje = new javax.swing.JLabel();
        lb_ruta = new javax.swing.JLabel();
        bt_salir = new javax.swing.JButton();
        lb_cant_asientos = new javax.swing.JLabel();
        cb_cant_asientos = new javax.swing.JComboBox<>();
        tb_total = new javax.swing.JTextField();
        lb_total = new javax.swing.JLabel();
        bt_vender = new javax.swing.JButton();
        lb_precio_asiento = new javax.swing.JLabel();
        tb_precio_asiento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        cb_ruta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_rutaItemStateChanged(evt);
            }
        });
        cb_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_rutaActionPerformed(evt);
            }
        });

        cb_viaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_viajeItemStateChanged(evt);
            }
        });
        cb_viaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_viajeActionPerformed(evt);
            }
        });

        lb_viaje.setText("Viaje");

        lb_ruta.setText("Ruta del viaje");

        bt_salir.setText("Salir");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        lb_cant_asientos.setText("Cantidad de asientos");

        cb_cant_asientos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_cant_asientosItemStateChanged(evt);
            }
        });

        tb_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_totalActionPerformed(evt);
            }
        });

        lb_total.setText("Total");

        bt_vender.setText("Vender");
        bt_vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_venderActionPerformed(evt);
            }
        });

        lb_precio_asiento.setText("Precio del asiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bt_vender, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(bt_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(lb_cant_asientos)
                            .addGap(18, 18, 18)
                            .addComponent(cb_cant_asientos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lb_ruta)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(lb_viaje, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb_ruta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_viaje, 0, 127, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(lb_precio_asiento)
                            .addGap(27, 27, 27)
                            .addComponent(tb_precio_asiento, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(tb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lb_ruta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cb_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_viaje)
                    .addComponent(cb_viaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cant_asientos)
                    .addComponent(cb_cant_asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lb_precio_asiento)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_precio_asiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_total)
                    .addComponent(tb_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_salir)
                    .addComponent(bt_vender))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_totalActionPerformed

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        // TODO add your handling code here:
        Menu_principal mp = new Menu_principal();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_salirActionPerformed

    private void cb_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_rutaActionPerformed
        
    }//GEN-LAST:event_cb_rutaActionPerformed

    private void cb_viajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_viajeActionPerformed
        
    }//GEN-LAST:event_cb_viajeActionPerformed

    private void cb_rutaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_rutaItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {   
            int codigo_ruta;
            codigo_ruta = Funciones.extraer_codigo((String) cb_ruta.getSelectedItem());
        
            try {
                llenar_cb_viajes(codigo_ruta);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Venta_tickets.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cb_rutaItemStateChanged

    private void cb_viajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_viajeItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            try {
                // TODO add your handling code here:
                int codigo_viaje;
                codigo_viaje = Funciones.extraer_codigo((String) cb_viaje.getSelectedItem());
            
                llenar_cb_cant_asientos(codigo_viaje);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Venta_tickets.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cb_viajeItemStateChanged

    private void cb_cant_asientosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_cant_asientosItemStateChanged
        // TODO add your handling code here
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            int codigo_viaje;
            codigo_viaje = Funciones.extraer_codigo((String) cb_viaje.getSelectedItem());
        
            try {
                llenar_tb_precio_asiento(codigo_viaje);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Venta_tickets.class.getName()).log(Level.SEVERE, null, ex);
            }
            llenar_tb_total();
        }
    }//GEN-LAST:event_cb_cant_asientosItemStateChanged

    private void bt_venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_venderActionPerformed
        // TODO add your handling code here:
        if(cb_ruta.getItemCount() < 1)
        {
            JOptionPane.showMessageDialog(this,"No hay Ruta seleccionada, no puede vender tickets sin rutas");
            return;
        }
        
        if(cb_viaje.getItemCount() < 1)
        {
            JOptionPane.showMessageDialog(this,"No hay viaje seleccionado, no puede vender tickets su viaje");
            return;
        }
        
        if(cb_cant_asientos.getItemCount() < 1)
        {
            JOptionPane.showMessageDialog(this,"No hay asientos Disponibles en este viaje");
            return;
        }
        
        Archivo arc = new Archivo();
        ArrayList<Viajes> lista_viajes = new ArrayList<>();
        Autobus au = new Autobus();
        int codigo_autobus;
        
        int codigo_ticket = 0;
        int codigo_viaje;
        int codigo_usuario;
        int fila;
        int columna;
        String fecha;
        String hora;
        
        try {
            lista_viajes = arc.leer_archivo("Viajes");
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Venta_tickets.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        codigo_viaje = Funciones.extraer_codigo((String) cb_viaje.getSelectedItem());
        codigo_usuario = Funciones.usuario_general.getCodigo_usuario();
        java.util.Date fechas = new Date();
        fecha = fechas.toString();
        Calendar tiempo = new GregorianCalendar();
        hora = tiempo.toString();
        
        codigo_autobus = lista_viajes.get(codigo_viaje - 1).getCodigo_autobus();
        try {
            au = (Autobus) arc.buscar_archivo("Autobus", codigo_autobus);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Venta_tickets.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int stop = (Integer.decode((String) cb_cant_asientos.getSelectedItem()));
        
        for(int c=0; c < stop ;c++)
        {
            try {
                codigo_ticket = Funciones.generar_codigo_automatico("Tickets");
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Venta_tickets.class.getName()).log(Level.SEVERE, null, ex);
            }
            int v[] = {1,1};
            try {
                v = Funciones.generar_proximo_asiento((au.getCant_filas()),codigo_viaje);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Venta_tickets.class.getName()).log(Level.SEVERE, null, ex);
            }
            fila = v[0];
            columna = v[1];
            Tickets t = new Tickets(codigo_ticket,codigo_viaje,codigo_usuario,fila,columna,fecha,hora,true);
            System.out.println("Se vendio el Ticket: " + t.getCodigo_ticket() + " en el asiento: "
                            + t.getFila() + "," + t.getColumna());
            arc.insertar_archivo("Tickets", t);
            
            try {
                Funciones.Ticket_general = t;
                Impresion_ticket it = new Impresion_ticket();
                it.setVisible(true);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Venta_tickets.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                llenar_cb_rutas();
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Venta_tickets.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bt_venderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta_tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta_tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta_tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta_tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Venta_tickets().setVisible(true);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Venta_tickets.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    public void llenar_cb_rutas() throws IOException, FileNotFoundException, ClassNotFoundException
    {
        cb_ruta.removeAllItems();
        Archivo arc = new Archivo();
        ArrayList<Rutas> lista_rutas;
        
        lista_rutas = arc.leer_archivo("Rutas");
        
        for(Rutas elemento : lista_rutas)
        {
            if(elemento.isEstado())
            {
                cb_ruta.addItem(Integer.toString(elemento.getCodigo_ruta()) + " " + elemento.getLugar_llegada());
            }
        }
    }
    
    public void llenar_cb_viajes(int codigo_ruta) throws IOException, FileNotFoundException, ClassNotFoundException
    {
        cb_viaje.removeAllItems();
        Archivo arc = new Archivo();
        ArrayList<Viajes> lista_viajes;
        
        lista_viajes = arc.leer_archivo("Viajes");
        
        for(Viajes elemento : lista_viajes)
        {
            if(elemento.getCodigo_ruta() == codigo_ruta && elemento.isEstado() == true)
            {
                cb_viaje.addItem(Integer.toString(elemento.getCodigo_viaje()) + " " + elemento.getHora_salida());
            }
        }
    }
    
    public void llenar_cb_cant_asientos(int codigo_viaje) throws IOException, FileNotFoundException, ClassNotFoundException
    {
        cb_cant_asientos.removeAllItems();
        int asientos_vendidos = 0;
        int cant_asientos;
        int codigo_autobus;
        Archivo arc = new Archivo();
        ArrayList<Tickets> lista_tickets;
        ArrayList<Viajes> lista_viajes;
        Autobus au;
        
        lista_tickets = arc.leer_archivo("Tickets");
        lista_viajes = arc.leer_archivo("Viajes");
        codigo_autobus = lista_viajes.get(codigo_viaje - 1).getCodigo_autobus();
        au = (Autobus) arc.buscar_archivo("Autobus", codigo_autobus);
        
        for(Tickets elemento : lista_tickets)
        {
            if(elemento.getCodigo_viaje() == codigo_viaje)
            {
                asientos_vendidos++;
            }
        }
        
        cant_asientos = (au.getCant_filas() * 4) - (asientos_vendidos);
        
        for(int c=1;c<= cant_asientos;c++)
        {
            cb_cant_asientos.addItem(Integer.toString(c));
        }
    }
    
    public void llenar_tb_precio_asiento(int codigo_viaje) throws IOException, FileNotFoundException, ClassNotFoundException
    {
        Archivo arc = new Archivo();
        ArrayList<Viajes> lista_viajes;
        
        lista_viajes = arc.leer_archivo("Viajes");
        
        tb_precio_asiento.setText(String.valueOf(lista_viajes.get(codigo_viaje - 1).getPrecio_ticket()));
    }
    
    public void llenar_tb_total()
    {
        float total;
        
        total = (Float.valueOf(tb_precio_asiento.getText()) * (Float.valueOf((String) cb_cant_asientos.getSelectedItem())));
        tb_total.setText(String.valueOf(total));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_salir;
    private javax.swing.JButton bt_vender;
    private javax.swing.JComboBox<String> cb_cant_asientos;
    private javax.swing.JComboBox<String> cb_ruta;
    private javax.swing.JComboBox<String> cb_viaje;
    private javax.swing.JLabel lb_cant_asientos;
    private javax.swing.JLabel lb_precio_asiento;
    private javax.swing.JLabel lb_ruta;
    private javax.swing.JLabel lb_total;
    private javax.swing.JLabel lb_viaje;
    private javax.swing.JTextField tb_precio_asiento;
    private javax.swing.JTextField tb_total;
    // End of variables declaration//GEN-END:variables

    private ComboBoxModel<String> DefaultComboBoxModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private ComboBoxModel<String> DefaulComboBoxModel(String[] lista) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
